package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ChristianZone generated by hbm2java
 */
public class ChristianZone  implements java.io.Serializable {


     private Integer id;
     private Zone zone;
     private Christian christian;
     private Date createdOn;
     private char isActive;

    public ChristianZone() {
    }

    public ChristianZone(Zone zone, Christian christian, Date createdOn, char isActive) {
       this.zone = zone;
       this.christian = christian;
       this.createdOn = createdOn;
       this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Zone getZone() {
        return this.zone;
    }
    
    public void setZone(Zone zone) {
        this.zone = zone;
    }
    public Christian getChristian() {
        return this.christian;
    }
    
    public void setChristian(Christian christian) {
        this.christian = christian;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }




}


