package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA



/**
 * ChristianContact generated by hbm2java
 */
public class ChristianContact  implements java.io.Serializable {


     private int christian;
     private Christian christian_1;
     private String phoneNumber;
     private String otherTelephone;
     private String email;
     private String otherEmail;

    public ChristianContact() {
    }

	
    public ChristianContact(int christian, Christian christian_1, String phoneNumber, String email) {
        this.christian = christian;
        this.christian_1 = christian_1;
        this.phoneNumber = phoneNumber;
        this.email = email;
    }
    public ChristianContact(int christian, Christian christian_1, String phoneNumber, String otherTelephone, String email, String otherEmail) {
       this.christian = christian;
       this.christian_1 = christian_1;
       this.phoneNumber = phoneNumber;
       this.otherTelephone = otherTelephone;
       this.email = email;
       this.otherEmail = otherEmail;
    }
   
    public int getChristian() {
        return this.christian;
    }
    
    public void setChristian(int christian) {
        this.christian = christian;
    }
    public Christian getChristian_1() {
        return this.christian_1;
    }
    
    public void setChristian_1(Christian christian_1) {
        this.christian_1 = christian_1;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getOtherTelephone() {
        return this.otherTelephone;
    }
    
    public void setOtherTelephone(String otherTelephone) {
        this.otherTelephone = otherTelephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getOtherEmail() {
        return this.otherEmail;
    }
    
    public void setOtherEmail(String otherEmail) {
        this.otherEmail = otherEmail;
    }




}


