package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ChristianSacrement generated by hbm2java
 */
public class ChristianSacrement  implements java.io.Serializable {


     private ChristianSacrementId id;
     private Sacrement sacrement;
     private Christian christian;
     private Date celebrationDate;
     private String celebrant;
     private char celebratedHere;
     private String godParent;
     private String godParentParish;

    public ChristianSacrement() {
    }

    public ChristianSacrement(ChristianSacrementId id, Sacrement sacrement, Christian christian, Date celebrationDate, String celebrant, char celebratedHere, String godParent, String godParentParish) {
       this.id = id;
       this.sacrement = sacrement;
       this.christian = christian;
       this.celebrationDate = celebrationDate;
       this.celebrant = celebrant;
       this.celebratedHere = celebratedHere;
       this.godParent = godParent;
       this.godParentParish = godParentParish;
    }
   
    public ChristianSacrementId getId() {
        return this.id;
    }
    
    public void setId(ChristianSacrementId id) {
        this.id = id;
    }
    public Sacrement getSacrement() {
        return this.sacrement;
    }
    
    public void setSacrement(Sacrement sacrement) {
        this.sacrement = sacrement;
    }
    public Christian getChristian() {
        return this.christian;
    }
    
    public void setChristian(Christian christian) {
        this.christian = christian;
    }
    public Date getCelebrationDate() {
        return this.celebrationDate;
    }
    
    public void setCelebrationDate(Date celebrationDate) {
        this.celebrationDate = celebrationDate;
    }
    public String getCelebrant() {
        return this.celebrant;
    }
    
    public void setCelebrant(String celebrant) {
        this.celebrant = celebrant;
    }
    public char getCelebratedHere() {
        return this.celebratedHere;
    }
    
    public void setCelebratedHere(char celebratedHere) {
        this.celebratedHere = celebratedHere;
    }
    public String getGodParent() {
        return this.godParent;
    }
    
    public void setGodParent(String godParent) {
        this.godParent = godParent;
    }
    public String getGodParentParish() {
        return this.godParentParish;
    }
    
    public void setGodParentParish(String godParentParish) {
        this.godParentParish = godParentParish;
    }




}


