package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EventType generated by hbm2java
 */
public class EventType  implements java.io.Serializable {


     private Integer eventTypeId;
     private String designation;
     private String periodicity;
     private Date createdOn;
     private Set eventDetails = new HashSet(0);

    public EventType() {
    }

	
    public EventType(String designation, String periodicity, Date createdOn) {
        this.designation = designation;
        this.periodicity = periodicity;
        this.createdOn = createdOn;
    }
    public EventType(String designation, String periodicity, Date createdOn, Set eventDetails) {
       this.designation = designation;
       this.periodicity = periodicity;
       this.createdOn = createdOn;
       this.eventDetails = eventDetails;
    }
   
    public Integer getEventTypeId() {
        return this.eventTypeId;
    }
    
    public void setEventTypeId(Integer eventTypeId) {
        this.eventTypeId = eventTypeId;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getPeriodicity() {
        return this.periodicity;
    }
    
    public void setPeriodicity(String periodicity) {
        this.periodicity = periodicity;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Set getEventDetails() {
        return this.eventDetails;
    }
    
    public void setEventDetails(Set eventDetails) {
        this.eventDetails = eventDetails;
    }




}


