package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EventIncome generated by hbm2java
 */
public class EventIncome  implements java.io.Serializable {


     private Integer EIncomeId;
     private EventDetail eventDetail;
     private User user;
     private Date createdOn;
     private int income;

    public EventIncome() {
    }

    public EventIncome(EventDetail eventDetail, User user, Date createdOn, int income) {
       this.eventDetail = eventDetail;
       this.user = user;
       this.createdOn = createdOn;
       this.income = income;
    }
   
    public Integer getEIncomeId() {
        return this.EIncomeId;
    }
    
    public void setEIncomeId(Integer EIncomeId) {
        this.EIncomeId = EIncomeId;
    }
    public EventDetail getEventDetail() {
        return this.eventDetail;
    }
    
    public void setEventDetail(EventDetail eventDetail) {
        this.eventDetail = eventDetail;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public int getIncome() {
        return this.income;
    }
    
    public void setIncome(int income) {
        this.income = income;
    }




}


