package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LoanType generated by hbm2java
 */
public class LoanType  implements java.io.Serializable {


     private Integer loanTypeId;
     private String loanTypeName;
     private Set loans = new HashSet(0);

    public LoanType() {
    }

	
    public LoanType(String loanTypeName) {
        this.loanTypeName = loanTypeName;
    }
    public LoanType(String loanTypeName, Set loans) {
       this.loanTypeName = loanTypeName;
       this.loans = loans;
    }
   
    public Integer getLoanTypeId() {
        return this.loanTypeId;
    }
    
    public void setLoanTypeId(Integer loanTypeId) {
        this.loanTypeId = loanTypeId;
    }
    public String getLoanTypeName() {
        return this.loanTypeName;
    }
    
    public void setLoanTypeName(String loanTypeName) {
        this.loanTypeName = loanTypeName;
    }
    public Set getLoans() {
        return this.loans;
    }
    
    public void setLoans(Set loans) {
        this.loans = loans;
    }




}


