package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private Integer loanId;
     private LoanType loanType;
     private Christian christian;
     private int loanAmount;
     private Date loanDate;
     private String loanCode;
     private int interestRate;
     private Date refundDeadline;
     private char refundStatus;
     private int amountToRepay;
     private Set loanRefundings = new HashSet(0);

    public Loan() {
    }

	
    public Loan(LoanType loanType, Christian christian, int loanAmount, Date loanDate, String loanCode, int interestRate, Date refundDeadline, char refundStatus, int amountToRepay) {
        this.loanType = loanType;
        this.christian = christian;
        this.loanAmount = loanAmount;
        this.loanDate = loanDate;
        this.loanCode = loanCode;
        this.interestRate = interestRate;
        this.refundDeadline = refundDeadline;
        this.refundStatus = refundStatus;
        this.amountToRepay = amountToRepay;
    }
    public Loan(LoanType loanType, Christian christian, int loanAmount, Date loanDate, String loanCode, int interestRate, Date refundDeadline, char refundStatus, int amountToRepay, Set loanRefundings) {
       this.loanType = loanType;
       this.christian = christian;
       this.loanAmount = loanAmount;
       this.loanDate = loanDate;
       this.loanCode = loanCode;
       this.interestRate = interestRate;
       this.refundDeadline = refundDeadline;
       this.refundStatus = refundStatus;
       this.amountToRepay = amountToRepay;
       this.loanRefundings = loanRefundings;
    }
   
    public Integer getLoanId() {
        return this.loanId;
    }
    
    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }
    public LoanType getLoanType() {
        return this.loanType;
    }
    
    public void setLoanType(LoanType loanType) {
        this.loanType = loanType;
    }
    public Christian getChristian() {
        return this.christian;
    }
    
    public void setChristian(Christian christian) {
        this.christian = christian;
    }
    public int getLoanAmount() {
        return this.loanAmount;
    }
    
    public void setLoanAmount(int loanAmount) {
        this.loanAmount = loanAmount;
    }
    public Date getLoanDate() {
        return this.loanDate;
    }
    
    public void setLoanDate(Date loanDate) {
        this.loanDate = loanDate;
    }
    public String getLoanCode() {
        return this.loanCode;
    }
    
    public void setLoanCode(String loanCode) {
        this.loanCode = loanCode;
    }
    public int getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(int interestRate) {
        this.interestRate = interestRate;
    }
    public Date getRefundDeadline() {
        return this.refundDeadline;
    }
    
    public void setRefundDeadline(Date refundDeadline) {
        this.refundDeadline = refundDeadline;
    }
    public char getRefundStatus() {
        return this.refundStatus;
    }
    
    public void setRefundStatus(char refundStatus) {
        this.refundStatus = refundStatus;
    }
    public int getAmountToRepay() {
        return this.amountToRepay;
    }
    
    public void setAmountToRepay(int amountToRepay) {
        this.amountToRepay = amountToRepay;
    }
    public Set getLoanRefundings() {
        return this.loanRefundings;
    }
    
    public void setLoanRefundings(Set loanRefundings) {
        this.loanRefundings = loanRefundings;
    }




}


