package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ministry generated by hbm2java
 */
public class Ministry  implements java.io.Serializable {


     private Integer ministryId;
     private String designation;
     private String description;
     private String frequency;
     private String startTime;
     private String serviceDuration;
     private String concernedGroup;
     private char status;
     private Set ministryDetails = new HashSet(0);

    public Ministry() {
    }

	
    public Ministry(String designation, String description, String frequency, String startTime, String serviceDuration, String concernedGroup, char status) {
        this.designation = designation;
        this.description = description;
        this.frequency = frequency;
        this.startTime = startTime;
        this.serviceDuration = serviceDuration;
        this.concernedGroup = concernedGroup;
        this.status = status;
    }
    public Ministry(String designation, String description, String frequency, String startTime, String serviceDuration, String concernedGroup, char status, Set ministryDetails) {
       this.designation = designation;
       this.description = description;
       this.frequency = frequency;
       this.startTime = startTime;
       this.serviceDuration = serviceDuration;
       this.concernedGroup = concernedGroup;
       this.status = status;
       this.ministryDetails = ministryDetails;
    }
   
    public Integer getMinistryId() {
        return this.ministryId;
    }
    
    public void setMinistryId(Integer ministryId) {
        this.ministryId = ministryId;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }
    public String getServiceDuration() {
        return this.serviceDuration;
    }
    
    public void setServiceDuration(String serviceDuration) {
        this.serviceDuration = serviceDuration;
    }
    public String getConcernedGroup() {
        return this.concernedGroup;
    }
    
    public void setConcernedGroup(String concernedGroup) {
        this.concernedGroup = concernedGroup;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public Set getMinistryDetails() {
        return this.ministryDetails;
    }
    
    public void setMinistryDetails(Set ministryDetails) {
        this.ministryDetails = ministryDetails;
    }




}


