package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MinistryDetail generated by hbm2java
 */
public class MinistryDetail  implements java.io.Serializable {


     private Integer detailId;
     private Parish parish;
     private Ministry ministry;
     private String mainSpeaker;
     private String theme;
     private Date heldOn;
     private String summary;

    public MinistryDetail() {
    }

	
    public MinistryDetail(Parish parish, Ministry ministry, String mainSpeaker, String theme, Date heldOn) {
        this.parish = parish;
        this.ministry = ministry;
        this.mainSpeaker = mainSpeaker;
        this.theme = theme;
        this.heldOn = heldOn;
    }
    public MinistryDetail(Parish parish, Ministry ministry, String mainSpeaker, String theme, Date heldOn, String summary) {
       this.parish = parish;
       this.ministry = ministry;
       this.mainSpeaker = mainSpeaker;
       this.theme = theme;
       this.heldOn = heldOn;
       this.summary = summary;
    }
   
    public Integer getDetailId() {
        return this.detailId;
    }
    
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }
    public Parish getParish() {
        return this.parish;
    }
    
    public void setParish(Parish parish) {
        this.parish = parish;
    }
    public Ministry getMinistry() {
        return this.ministry;
    }
    
    public void setMinistry(Ministry ministry) {
        this.ministry = ministry;
    }
    public String getMainSpeaker() {
        return this.mainSpeaker;
    }
    
    public void setMainSpeaker(String mainSpeaker) {
        this.mainSpeaker = mainSpeaker;
    }
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }
    public Date getHeldOn() {
        return this.heldOn;
    }
    
    public void setHeldOn(Date heldOn) {
        this.heldOn = heldOn;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }




}


