package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Outflow generated by hbm2java
 */
public class Outflow  implements java.io.Serializable {


     private Integer outflowId;
     private OutflowType outflowType;
     private User user;
     private int outflowAmount;
     private String checkNumber;
     private Date outflowDate;
     private String outflowReference;

    public Outflow() {
    }

    public Outflow(OutflowType outflowType, User user, int outflowAmount, String checkNumber, Date outflowDate, String outflowReference) {
       this.outflowType = outflowType;
       this.user = user;
       this.outflowAmount = outflowAmount;
       this.checkNumber = checkNumber;
       this.outflowDate = outflowDate;
       this.outflowReference = outflowReference;
    }
   
    public Integer getOutflowId() {
        return this.outflowId;
    }
    
    public void setOutflowId(Integer outflowId) {
        this.outflowId = outflowId;
    }
    public OutflowType getOutflowType() {
        return this.outflowType;
    }
    
    public void setOutflowType(OutflowType outflowType) {
        this.outflowType = outflowType;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getOutflowAmount() {
        return this.outflowAmount;
    }
    
    public void setOutflowAmount(int outflowAmount) {
        this.outflowAmount = outflowAmount;
    }
    public String getCheckNumber() {
        return this.checkNumber;
    }
    
    public void setCheckNumber(String checkNumber) {
        this.checkNumber = checkNumber;
    }
    public Date getOutflowDate() {
        return this.outflowDate;
    }
    
    public void setOutflowDate(Date outflowDate) {
        this.outflowDate = outflowDate;
    }
    public String getOutflowReference() {
        return this.outflowReference;
    }
    
    public void setOutflowReference(String outflowReference) {
        this.outflowReference = outflowReference;
    }




}


