package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Parish generated by hbm2java
 */
public class Parish  implements java.io.Serializable {


     private Integer parishId;
     private String parishName;
     private int foundationYear;
     private String location;
     private Set christians = new HashSet(0);
     private Set ministryDetails = new HashSet(0);
     private Set parishPastors = new HashSet(0);

    public Parish() {
    }

	
    public Parish(String parishName, int foundationYear, String location) {
        this.parishName = parishName;
        this.foundationYear = foundationYear;
        this.location = location;
    }
    public Parish(String parishName, int foundationYear, String location, Set christians, Set ministryDetails, Set parishPastors) {
       this.parishName = parishName;
       this.foundationYear = foundationYear;
       this.location = location;
       this.christians = christians;
       this.ministryDetails = ministryDetails;
       this.parishPastors = parishPastors;
    }
   
    public Integer getParishId() {
        return this.parishId;
    }
    
    public void setParishId(Integer parishId) {
        this.parishId = parishId;
    }
    public String getParishName() {
        return this.parishName;
    }
    
    public void setParishName(String parishName) {
        this.parishName = parishName;
    }
    public int getFoundationYear() {
        return this.foundationYear;
    }
    
    public void setFoundationYear(int foundationYear) {
        this.foundationYear = foundationYear;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set getChristians() {
        return this.christians;
    }
    
    public void setChristians(Set christians) {
        this.christians = christians;
    }
    public Set getMinistryDetails() {
        return this.ministryDetails;
    }
    
    public void setMinistryDetails(Set ministryDetails) {
        this.ministryDetails = ministryDetails;
    }
    public Set getParishPastors() {
        return this.parishPastors;
    }
    
    public void setParishPastors(Set parishPastors) {
        this.parishPastors = parishPastors;
    }




}


