package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pastor generated by hbm2java
 */
public class Pastor  implements java.io.Serializable {


     private Integer pastorId;
     private String firstName;
     private String lastName;
     private char gender;
     private String educationLevel;
     private char maritalStatus;
     private String spouseName;
     private String pastorshipCode;
     private Set weddings = new HashSet(0);
     private Set parishPastors = new HashSet(0);

    public Pastor() {
    }

	
    public Pastor(String firstName, String lastName, char gender, String educationLevel, char maritalStatus, String pastorshipCode) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.educationLevel = educationLevel;
        this.maritalStatus = maritalStatus;
        this.pastorshipCode = pastorshipCode;
    }
    public Pastor(String firstName, String lastName, char gender, String educationLevel, char maritalStatus, String spouseName, String pastorshipCode, Set weddings, Set parishPastors) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.educationLevel = educationLevel;
       this.maritalStatus = maritalStatus;
       this.spouseName = spouseName;
       this.pastorshipCode = pastorshipCode;
       this.weddings = weddings;
       this.parishPastors = parishPastors;
    }
   
    public Integer getPastorId() {
        return this.pastorId;
    }
    
    public void setPastorId(Integer pastorId) {
        this.pastorId = pastorId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public char getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(char maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getSpouseName() {
        return this.spouseName;
    }
    
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }
    public String getPastorshipCode() {
        return this.pastorshipCode;
    }
    
    public void setPastorshipCode(String pastorshipCode) {
        this.pastorshipCode = pastorshipCode;
    }
    public Set getWeddings() {
        return this.weddings;
    }
    
    public void setWeddings(Set weddings) {
        this.weddings = weddings;
    }
    public Set getParishPastors() {
        return this.parishPastors;
    }
    
    public void setParishPastors(Set parishPastors) {
        this.parishPastors = parishPastors;
    }




}


