package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PrayerRequest generated by hbm2java
 */
public class PrayerRequest  implements java.io.Serializable {


     private Integer requestId;
     private Christian christian;
     private String prayerIntention;
     private Date requestDate;
     private String requestType;
     private Date preferedPrayerDate;

    public PrayerRequest() {
    }

    public PrayerRequest(Christian christian, String prayerIntention, Date requestDate, String requestType, Date preferedPrayerDate) {
       this.christian = christian;
       this.prayerIntention = prayerIntention;
       this.requestDate = requestDate;
       this.requestType = requestType;
       this.preferedPrayerDate = preferedPrayerDate;
    }
   
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
    public Christian getChristian() {
        return this.christian;
    }
    
    public void setChristian(Christian christian) {
        this.christian = christian;
    }
    public String getPrayerIntention() {
        return this.prayerIntention;
    }
    
    public void setPrayerIntention(String prayerIntention) {
        this.prayerIntention = prayerIntention;
    }
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    public String getRequestType() {
        return this.requestType;
    }
    
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }
    public Date getPreferedPrayerDate() {
        return this.preferedPrayerDate;
    }
    
    public void setPreferedPrayerDate(Date preferedPrayerDate) {
        this.preferedPrayerDate = preferedPrayerDate;
    }




}


