package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sacrement generated by hbm2java
 */
public class Sacrement  implements java.io.Serializable {


     private Integer sacramentId;
     private String sacramentName;
     private Set christianSacrements = new HashSet(0);

    public Sacrement() {
    }

	
    public Sacrement(String sacramentName) {
        this.sacramentName = sacramentName;
    }
    public Sacrement(String sacramentName, Set christianSacrements) {
       this.sacramentName = sacramentName;
       this.christianSacrements = christianSacrements;
    }
   
    public Integer getSacramentId() {
        return this.sacramentId;
    }
    
    public void setSacramentId(Integer sacramentId) {
        this.sacramentId = sacramentId;
    }
    public String getSacramentName() {
        return this.sacramentName;
    }
    
    public void setSacramentName(String sacramentName) {
        this.sacramentName = sacramentName;
    }
    public Set getChristianSacrements() {
        return this.christianSacrements;
    }
    
    public void setChristianSacrements(Set christianSacrements) {
        this.christianSacrements = christianSacrements;
    }




}


