package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA



/**
 * SupplyBillDetail generated by hbm2java
 */
public class SupplyBillDetail  implements java.io.Serializable {


     private Integer id;
     private SupplyBill supplyBill;
     private String billItem;
     private int billItemUnitPrice;
     private int billItemQuantity;

    public SupplyBillDetail() {
    }

    public SupplyBillDetail(SupplyBill supplyBill, String billItem, int billItemUnitPrice, int billItemQuantity) {
       this.supplyBill = supplyBill;
       this.billItem = billItem;
       this.billItemUnitPrice = billItemUnitPrice;
       this.billItemQuantity = billItemQuantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SupplyBill getSupplyBill() {
        return this.supplyBill;
    }
    
    public void setSupplyBill(SupplyBill supplyBill) {
        this.supplyBill = supplyBill;
    }
    public String getBillItem() {
        return this.billItem;
    }
    
    public void setBillItem(String billItem) {
        this.billItem = billItem;
    }
    public int getBillItemUnitPrice() {
        return this.billItemUnitPrice;
    }
    
    public void setBillItemUnitPrice(int billItemUnitPrice) {
        this.billItemUnitPrice = billItemUnitPrice;
    }
    public int getBillItemQuantity() {
        return this.billItemQuantity;
    }
    
    public void setBillItemQuantity(int billItemQuantity) {
        this.billItemQuantity = billItemQuantity;
    }




}


