package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer supplierId;
     private String designation;
     private String telephone;
     private String email;
     private String location;
     private Set supplyBills = new HashSet(0);
     private Set supplierItems = new HashSet(0);

    public Supplier() {
    }

	
    public Supplier(String designation, String telephone, String email, String location) {
        this.designation = designation;
        this.telephone = telephone;
        this.email = email;
        this.location = location;
    }
    public Supplier(String designation, String telephone, String email, String location, Set supplyBills, Set supplierItems) {
       this.designation = designation;
       this.telephone = telephone;
       this.email = email;
       this.location = location;
       this.supplyBills = supplyBills;
       this.supplierItems = supplierItems;
    }
   
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set getSupplyBills() {
        return this.supplyBills;
    }
    
    public void setSupplyBills(Set supplyBills) {
        this.supplyBills = supplyBills;
    }
    public Set getSupplierItems() {
        return this.supplierItems;
    }
    
    public void setSupplierItems(Set supplierItems) {
        this.supplierItems = supplierItems;
    }




}


