package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SupplierItem generated by hbm2java
 */
public class SupplierItem  implements java.io.Serializable {


     private Integer id;
     private Supplier supplier;
     private String item;
     private Date supplyDate;

    public SupplierItem() {
    }

    public SupplierItem(Supplier supplier, String item, Date supplyDate) {
       this.supplier = supplier;
       this.item = item;
       this.supplyDate = supplyDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Date getSupplyDate() {
        return this.supplyDate;
    }
    
    public void setSupplyDate(Date supplyDate) {
        this.supplyDate = supplyDate;
    }




}


