package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Wedding generated by hbm2java
 */
public class Wedding  implements java.io.Serializable {


     private Integer weddingId;
     private Pastor pastor;
     private String husband;
     private String husbandGodFather;
     private String wife;
     private String wifeGodMother;
     private Date weddingDay;
     private int ceremonyFees;
     private char weddingFeesPayStatus;
     private String weddingTime;
     private int weddingCautionFees;
     private char cautionRefundedStatus;
     private Date createdOn;
     private char weddingCautionPayStatus;
     private String weddingCode;
     private Character weddingStatus;

    public Wedding() {
    }

	
    public Wedding(String husband, String husbandGodFather, String wife, String wifeGodMother, Date weddingDay, int ceremonyFees, char weddingFeesPayStatus, String weddingTime, int weddingCautionFees, char cautionRefundedStatus, Date createdOn, char weddingCautionPayStatus, String weddingCode) {
        this.husband = husband;
        this.husbandGodFather = husbandGodFather;
        this.wife = wife;
        this.wifeGodMother = wifeGodMother;
        this.weddingDay = weddingDay;
        this.ceremonyFees = ceremonyFees;
        this.weddingFeesPayStatus = weddingFeesPayStatus;
        this.weddingTime = weddingTime;
        this.weddingCautionFees = weddingCautionFees;
        this.cautionRefundedStatus = cautionRefundedStatus;
        this.createdOn = createdOn;
        this.weddingCautionPayStatus = weddingCautionPayStatus;
        this.weddingCode = weddingCode;
    }
    public Wedding(Pastor pastor, String husband, String husbandGodFather, String wife, String wifeGodMother, Date weddingDay, int ceremonyFees, char weddingFeesPayStatus, String weddingTime, int weddingCautionFees, char cautionRefundedStatus, Date createdOn, char weddingCautionPayStatus, String weddingCode, Character weddingStatus) {
       this.pastor = pastor;
       this.husband = husband;
       this.husbandGodFather = husbandGodFather;
       this.wife = wife;
       this.wifeGodMother = wifeGodMother;
       this.weddingDay = weddingDay;
       this.ceremonyFees = ceremonyFees;
       this.weddingFeesPayStatus = weddingFeesPayStatus;
       this.weddingTime = weddingTime;
       this.weddingCautionFees = weddingCautionFees;
       this.cautionRefundedStatus = cautionRefundedStatus;
       this.createdOn = createdOn;
       this.weddingCautionPayStatus = weddingCautionPayStatus;
       this.weddingCode = weddingCode;
       this.weddingStatus = weddingStatus;
    }
   
    public Integer getWeddingId() {
        return this.weddingId;
    }
    
    public void setWeddingId(Integer weddingId) {
        this.weddingId = weddingId;
    }
    public Pastor getPastor() {
        return this.pastor;
    }
    
    public void setPastor(Pastor pastor) {
        this.pastor = pastor;
    }
    public String getHusband() {
        return this.husband;
    }
    
    public void setHusband(String husband) {
        this.husband = husband;
    }
    public String getHusbandGodFather() {
        return this.husbandGodFather;
    }
    
    public void setHusbandGodFather(String husbandGodFather) {
        this.husbandGodFather = husbandGodFather;
    }
    public String getWife() {
        return this.wife;
    }
    
    public void setWife(String wife) {
        this.wife = wife;
    }
    public String getWifeGodMother() {
        return this.wifeGodMother;
    }
    
    public void setWifeGodMother(String wifeGodMother) {
        this.wifeGodMother = wifeGodMother;
    }
    public Date getWeddingDay() {
        return this.weddingDay;
    }
    
    public void setWeddingDay(Date weddingDay) {
        this.weddingDay = weddingDay;
    }
    public int getCeremonyFees() {
        return this.ceremonyFees;
    }
    
    public void setCeremonyFees(int ceremonyFees) {
        this.ceremonyFees = ceremonyFees;
    }
    public char getWeddingFeesPayStatus() {
        return this.weddingFeesPayStatus;
    }
    
    public void setWeddingFeesPayStatus(char weddingFeesPayStatus) {
        this.weddingFeesPayStatus = weddingFeesPayStatus;
    }
    public String getWeddingTime() {
        return this.weddingTime;
    }
    
    public void setWeddingTime(String weddingTime) {
        this.weddingTime = weddingTime;
    }
    public int getWeddingCautionFees() {
        return this.weddingCautionFees;
    }
    
    public void setWeddingCautionFees(int weddingCautionFees) {
        this.weddingCautionFees = weddingCautionFees;
    }
    public char getCautionRefundedStatus() {
        return this.cautionRefundedStatus;
    }
    
    public void setCautionRefundedStatus(char cautionRefundedStatus) {
        this.cautionRefundedStatus = cautionRefundedStatus;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public char getWeddingCautionPayStatus() {
        return this.weddingCautionPayStatus;
    }
    
    public void setWeddingCautionPayStatus(char weddingCautionPayStatus) {
        this.weddingCautionPayStatus = weddingCautionPayStatus;
    }
    public String getWeddingCode() {
        return this.weddingCode;
    }
    
    public void setWeddingCode(String weddingCode) {
        this.weddingCode = weddingCode;
    }
    public Character getWeddingStatus() {
        return this.weddingStatus;
    }
    
    public void setWeddingStatus(Character weddingStatus) {
        this.weddingStatus = weddingStatus;
    }




}


