package orm;
// Generated Jun 18, 2012 3:59:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone  implements java.io.Serializable {


     private Integer zoneId;
     private String zoneName;
     private Set christianZones = new HashSet(0);

    public Zone() {
    }

	
    public Zone(String zoneName) {
        this.zoneName = zoneName;
    }
    public Zone(String zoneName, Set christianZones) {
       this.zoneName = zoneName;
       this.christianZones = christianZones;
    }
   
    public Integer getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public Set getChristianZones() {
        return this.christianZones;
    }
    
    public void setChristianZones(Set christianZones) {
        this.christianZones = christianZones;
    }




}


