/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdministrationModule.java
 *
 * Created on May 1, 2012, 9:09:39 AM
 */
package orm.dao.Impl.GUI;

import java.util.Date;
import java.util.List;
import orm.DAOFactory;
import orm.UserLog;

/**
 *
 * @author jean pierre
 */
public class AdministrationModule extends javax.swing.JFrame {

    private E_CHURCH log;
    private String currentUser;
    private DAOFactory daoFactory = DAOFactory.getInstance();

    /**
     * Creates new form AdministrationModule
     */
    public AdministrationModule() {
        initComponents();
        this.setLocationRelativeTo(null);
        disabler();
    }

    public void setCurrent_user(String current_user) {
        this.currentUser = current_user;
    }

    private void disabler() {
        smParish.setEnabled(false);
        smSacrament.setEnabled(false);
        smEventType.setEnabled(false);
        smMinistryType.setEnabled(false);
        smOffertoryType.setEnabled(false);
        smSetLogo.setEnabled(false);
        smUser.setEnabled(false);
        smUserRole.setEnabled(false);
        smLogs.setEnabled(false);
    }

    public void enabler(List<String> roles) {
        for (String role : roles) {
            //System.out.println(role);
            if (role.equals("SYADM")) {
                enableAll();
                break;
            }
        }

    }

    private void enableAll() {
        smParish.setEnabled(true);
        smSacrament.setEnabled(true);
        smEventType.setEnabled(true);
        smMinistryType.setEnabled(true);
        smOffertoryType.setEnabled(true);
        smSetLogo.setEnabled(true);
        smUser.setEnabled(true);
        smUserRole.setEnabled(true);
        smLogs.setEnabled(true);
    }

    public E_CHURCH getLog() {
        return log;
    }

    public void setLog(E_CHURCH log) {
        this.log = log;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smParish = new javax.swing.JMenuItem();
        smSacrament = new javax.swing.JMenuItem();
        smEventType = new javax.swing.JMenuItem();
        smMinistryType = new javax.swing.JMenuItem();
        smOffertoryType = new javax.swing.JMenuItem();
        smSetLogo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smUser = new javax.swing.JMenuItem();
        smUserRole = new javax.swing.JMenuItem();
        smLogs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Basic Settings");
        jMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jMenu1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        smParish.setText("Parish");
        smParish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smParishActionPerformed(evt);
            }
        });
        jMenu1.add(smParish);

        smSacrament.setText("Sacrament");
        smSacrament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSacramentActionPerformed(evt);
            }
        });
        jMenu1.add(smSacrament);

        smEventType.setText("Types of Events");
        smEventType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEventTypeActionPerformed(evt);
            }
        });
        jMenu1.add(smEventType);

        smMinistryType.setText("Types of Ministries");
        smMinistryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smMinistryTypeActionPerformed(evt);
            }
        });
        jMenu1.add(smMinistryType);

        smOffertoryType.setText("Types of Offertories");
        smOffertoryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smOffertoryTypeActionPerformed(evt);
            }
        });
        jMenu1.add(smOffertoryType);

        smSetLogo.setText("Set Logo");
        smSetLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSetLogoActionPerformed(evt);
            }
        });
        jMenu1.add(smSetLogo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administration");

        smUser.setText("Users");
        smUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smUserActionPerformed(evt);
            }
        });
        jMenu2.add(smUser);

        smUserRole.setText("Assign Roles to Users");
        smUserRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smUserRoleActionPerformed(evt);
            }
        });
        jMenu2.add(smUserRole);

        smLogs.setText("Users Logs Editing");
        smLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLogsActionPerformed(evt);
            }
        });
        jMenu2.add(smLogs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenu1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu1AncestorMoved
// TODO add your handling code here:
}//GEN-LAST:event_jMenu1AncestorMoved

private void smParishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smParishActionPerformed
    ParishGUI parishGUI = new ParishGUI();
    add(parishGUI);
    parishGUI.show();

}//GEN-LAST:event_smParishActionPerformed

private void smSacramentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smSacramentActionPerformed
    SacrementGUI sacrementGUI = new SacrementGUI();
    add(sacrementGUI);
    sacrementGUI.show();
}//GEN-LAST:event_smSacramentActionPerformed

private void smEventTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEventTypeActionPerformed
    EventTypeGUI eventTypeGUI = new EventTypeGUI();
    add(eventTypeGUI);
    eventTypeGUI.show();
}//GEN-LAST:event_smEventTypeActionPerformed

private void smMinistryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smMinistryTypeActionPerformed
    MinistryGUI ministryGUI = new MinistryGUI();
    add(ministryGUI);
    ministryGUI.show();
}//GEN-LAST:event_smMinistryTypeActionPerformed

private void smOffertoryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smOffertoryTypeActionPerformed
    OffertoryTypeGUI offertoryTypeGUI = new OffertoryTypeGUI();
    add(offertoryTypeGUI);
    offertoryTypeGUI.show();
}//GEN-LAST:event_smOffertoryTypeActionPerformed

private void smUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smUserActionPerformed
    UserGUI userGUI = new UserGUI();
    add(userGUI);
    userGUI.show();
}//GEN-LAST:event_smUserActionPerformed

private void smUserRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smUserRoleActionPerformed
    UserRoleGUI userRoleGUI = new UserRoleGUI();
    add(userRoleGUI);
    userRoleGUI.show();
}//GEN-LAST:event_smUserRoleActionPerformed

private void smLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLogsActionPerformed
    UserLogGUI userLogGUI = new UserLogGUI();
    add(userLogGUI);
    userLogGUI.show();
}//GEN-LAST:event_smLogsActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    try {
//        UserLog userLog = daoFactory.getUserLogDAO().findLastLog(currentUser);
//        userLog.setLogout(new Date());
//        daoFactory.getUserLogDAO().saveOrUpdateLog(userLog);
        this.getLog().show();
        this.dispose();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_formWindowClosing

private void smSetLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smSetLogoActionPerformed
    new SetLogo().show();
}//GEN-LAST:event_smSetLogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdministrationModule().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem smEventType;
    private javax.swing.JMenuItem smLogs;
    private javax.swing.JMenuItem smMinistryType;
    private javax.swing.JMenuItem smOffertoryType;
    private javax.swing.JMenuItem smParish;
    private javax.swing.JMenuItem smSacrament;
    private javax.swing.JMenuItem smSetLogo;
    private javax.swing.JMenuItem smUser;
    private javax.swing.JMenuItem smUserRole;
    // End of variables declaration//GEN-END:variables
}
