/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinanceModule.java
 *
 * Created on May 1, 2012, 8:49:43 AM
 */
package orm.dao.Impl.GUI;

import java.util.Date;
import java.util.List;
import orm.DAOFactory;
import orm.UserLog;

/**
 *
 * @author jean pierre
 */
public class FinanceModule extends javax.swing.JFrame {

    private E_CHURCH log;
    private String currentUser;
    private DAOFactory daoFactory = DAOFactory.getInstance();

    /**
     * Creates new form FinanceModule
     */
    public FinanceModule() {
        initComponents();
        this.setLocationRelativeTo(null);
        disabler();
    }

    private void disabler() {
        smIncomeType.setEnabled(false);
        smOutflowType.setEnabled(false);
        smLoanType.setEnabled(false);
        smIncome.setEnabled(false);
        smOutflow.setEnabled(false);
        smReport.setEnabled(false);
        smLoan.setEnabled(false);
        smLoanReport.setEnabled(false);
        smRefunding.setEnabled(false);
    }

    private void enableReport() {
        smReport.setEnabled(true);
        smLoanReport.setEnabled(true);
    }

    private void enableAll() {
        smIncomeType.setEnabled(true);
        smOutflowType.setEnabled(true);
        smLoanType.setEnabled(true);
        smIncome.setEnabled(true);
        smOutflow.setEnabled(true);
        smReport.setEnabled(true);
        smLoan.setEnabled(true);
        smLoanReport.setEnabled(true);
        smRefunding.setEnabled(true);
    }

    private void enableAdmin() {
        smIncomeType.setEnabled(true);
        smOutflowType.setEnabled(true);
        smLoanType.setEnabled(true);
    }

    public void enabler(List<String> roles) {
        if (!roles.isEmpty()) {
            for (String role : roles) {
                if (role.equals("SYADM")) {
                    enableAdmin();
                }
                if (role.equals("PSR")) {
                    enableReport();
                }
                if (role.equals("ACT")) {
                    enableAll();
                }
            }
        }

    }

    public E_CHURCH getLog() {
        return log;
    }

    public void setLog(E_CHURCH log) {
        this.log = log;
    }

    public String getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smIncomeType = new javax.swing.JMenuItem();
        smOutflowType = new javax.swing.JMenuItem();
        smLoanType = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smIncome = new javax.swing.JMenuItem();
        smOutflow = new javax.swing.JMenuItem();
        smReport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        smLoan = new javax.swing.JMenuItem();
        smLoanReport = new javax.swing.JMenuItem();
        smRefunding = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Basic Settings");

        smIncomeType.setText("Income Type");
        smIncomeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smIncomeTypeActionPerformed(evt);
            }
        });
        jMenu1.add(smIncomeType);

        smOutflowType.setText("Expenses Type");
        smOutflowType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smOutflowTypeActionPerformed(evt);
            }
        });
        jMenu1.add(smOutflowType);

        smLoanType.setText("Loans Type");
        smLoanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLoanTypeActionPerformed(evt);
            }
        });
        jMenu1.add(smLoanType);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Accounting");

        smIncome.setText("Income");
        smIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smIncomeActionPerformed(evt);
            }
        });
        jMenu2.add(smIncome);

        smOutflow.setText("Expenses");
        smOutflow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smOutflowActionPerformed(evt);
            }
        });
        jMenu2.add(smOutflow);

        smReport.setText("Reports");
        smReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smReportActionPerformed(evt);
            }
        });
        jMenu2.add(smReport);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Loan Management");

        smLoan.setText("Loan Recording");
        smLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLoanActionPerformed(evt);
            }
        });
        jMenu3.add(smLoan);

        smLoanReport.setText("Loan Report");
        smLoanReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLoanReportActionPerformed(evt);
            }
        });
        jMenu3.add(smLoanReport);

        smRefunding.setText("Loan Refunding");
        smRefunding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smRefundingActionPerformed(evt);
            }
        });
        jMenu3.add(smRefunding);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    try {
//        UserLog userLog = daoFactory.getUserLogDAO().findLastLog(currentUser);
//        userLog.setLogout(new Date());
//        daoFactory.getUserLogDAO().saveOrUpdateLog(userLog);
        this.getLog().show();
        this.dispose();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_formWindowClosing

private void smIncomeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smIncomeTypeActionPerformed
    IncomeTypeGUI incomeTypeGUI = new IncomeTypeGUI();
    add(incomeTypeGUI);
    incomeTypeGUI.show();
}//GEN-LAST:event_smIncomeTypeActionPerformed

private void smOutflowTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smOutflowTypeActionPerformed
    OutflowTypeGUI outflowTypeGUI = new OutflowTypeGUI();
    add(outflowTypeGUI);
    outflowTypeGUI.show();
}//GEN-LAST:event_smOutflowTypeActionPerformed

private void smLoanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLoanTypeActionPerformed
    LoanTypeGUI loanTypeGUI = new LoanTypeGUI();
    add(loanTypeGUI);
    loanTypeGUI.show();
}//GEN-LAST:event_smLoanTypeActionPerformed

private void smIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smIncomeActionPerformed
    IncomeGUI incomeGUI = new IncomeGUI();
    incomeGUI.setEncoder(currentUser);
    add(incomeGUI);
    incomeGUI.show();
}//GEN-LAST:event_smIncomeActionPerformed

private void smOutflowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smOutflowActionPerformed
    OutflowGUI outflowGUI = new OutflowGUI();
    outflowGUI.setEncoder(currentUser);
    add(outflowGUI);
    outflowGUI.show();
}//GEN-LAST:event_smOutflowActionPerformed

private void smLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLoanActionPerformed
    LoanGUI loanGUI = new LoanGUI();
    loanGUI.setModule(this);
    loanGUI.setCashier(currentUser);
    add(loanGUI);
    loanGUI.show();
}//GEN-LAST:event_smLoanActionPerformed

private void smRefundingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smRefundingActionPerformed
    LoanRefundGUI refunding = new LoanRefundGUI();
    refunding.setCashier(currentUser);
    add(refunding);
    refunding.show();
}//GEN-LAST:event_smRefundingActionPerformed

private void smReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smReportActionPerformed
    AccountingReportGUI accountingReportGUI = new AccountingReportGUI();
    add(accountingReportGUI);
    accountingReportGUI.show();
}//GEN-LAST:event_smReportActionPerformed

private void smLoanReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLoanReportActionPerformed
    LoanReportGUI loanReportGUI = new LoanReportGUI();
    add(loanReportGUI);
    loanReportGUI.show();
}//GEN-LAST:event_smLoanReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FinanceModule().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem smIncome;
    private javax.swing.JMenuItem smIncomeType;
    private javax.swing.JMenuItem smLoan;
    private javax.swing.JMenuItem smLoanReport;
    private javax.swing.JMenuItem smLoanType;
    private javax.swing.JMenuItem smOutflow;
    private javax.swing.JMenuItem smOutflowType;
    private javax.swing.JMenuItem smRefunding;
    private javax.swing.JMenuItem smReport;
    // End of variables declaration//GEN-END:variables
}
