/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IncomeGUI.java
 *
 * Created on May 17, 2012, 4:37:38 PM
 */
package orm.dao.Impl.GUI;

import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import orm.DAOFactory;
import orm.Income;
import orm.IncomeType;
import orm.Notifier;

/**
 *
 * @author jean pierre
 */
public class IncomeGUI extends javax.swing.JInternalFrame {

    private DAOFactory daoFactory = DAOFactory.getInstance();
    private String encoder;

    /** Creates new form IncomeGUI */
    public IncomeGUI() {
        initComponents();
        setTypes();
    }

    private void setTypes() {
        cmbIncomeType.removeAllItems();
        for (IncomeType t : daoFactory.getIncomeTypeDAO().findAll()) {
            cmbIncomeType.addItem(t.getIncomeType());
        }
    }

    public void setEncoder(String encoder) {
        this.encoder = encoder;
        txtEncoder.setText(encoder);
    }

    private void clear() {
        cmbIncomeType.setSelectedIndex(0);
        txtIncomeAmount.setText(null);
        chDate.setDate(null);
        txtComment.setText(null);
        txtId.setText(null);
        txtReceiptNumber.setText(null);
    }

    private void search() {
        if (!txtReceiptNumber.getText().isEmpty()) {
            try {
                Income income = daoFactory.getIncomeDAO().findByReceiptNumber(txtReceiptNumber.getText());
                for (int i = 0; i < cmbIncomeType.getItemCount(); i++) {
                    if (income.getIncomeType().getIncomeType().equals(cmbIncomeType.getItemAt(i))) {
                        cmbIncomeType.setSelectedIndex(i);
                        break;
                    }
                }
                txtIncomeAmount.setText("" + income.getIncome());
                chDate.setDate(income.getIncomeDate());
                txtComment.setText(income.getIncomeComment());
                txtId.setText("" + income.getIncomeId());
                txtReceiptNumber.setText(income.getReceiptNumber());

            } catch (Exception ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Receipt number of the Payment you are searching");
        }
    }

    private void save() {
        if (chDate.getDate().after(new Date())) {
            JOptionPane.showMessageDialog(null, "Income Date cannot be greater that today's");
        } else {
            if (!txtComment.getText().equals("")) {
                if (!txtIncomeAmount.getText().isEmpty()) {
                    if (!txtReceiptNumber.getText().isEmpty()) {
                        Income income = new Income();
                        if (daoFactory.getIncomeDAO().findByReceiptNumber(txtReceiptNumber.getText()) != null) {
                            income = daoFactory.getIncomeDAO().findByReceiptNumber(txtReceiptNumber.getText());
                        }
                        income.setReceiptNumber(txtReceiptNumber.getText());
                        income.setIncomeType(daoFactory.getIncomeTypeDAO().findByName((String) cmbIncomeType.getSelectedItem()));
                        income.setIncome(Integer.parseInt(txtIncomeAmount.getText()));
                        income.setIncomeDate(chDate.getDate());
                        income.setIncomeComment(txtComment.getText());
                        income.setUser(daoFactory.getUserDAO().findByUsername(txtEncoder.getText()));
                        boolean done = daoFactory.getIncomeDAO().saveOrUpdateIncome(income);
                        if (done) {
                            int id = daoFactory.getIncomeDAO().findByReceiptNumber(txtReceiptNumber.getText()).getIncomeId();
                            txtId.setText("" + id);
                        }
                        Notifier.notifier(done);
                    } else {
                        JOptionPane.showMessageDialog(null, "Enter Receipt/Bordereau Number before attempting to save", "Receipt/Bordereau Number Missing", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Enter income amount before you attempt recording", "Income Missing", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Offertory Comment/Description is required.", "Recall Message", JOptionPane.WARNING_MESSAGE);
            }
        }

    }

    private void setBack(int choice) {
        if (choice == 0) {
            txtId.setEditable(true);
            txtId.setBackground(Color.WHITE);
        } else {
            if (choice == 0) {
                txtId.setEditable(false);
                txtId.setBackground(new Color(204, 204, 204));
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbIncomeType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtIncomeAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtEncoder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtReceiptNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Income");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Income", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 153, 0)));

        jLabel1.setText("Income Type:");

        cmbIncomeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Income Amount:");

        txtIncomeAmount.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIncomeAmountCaretUpdate(evt);
            }
        });

        jLabel3.setText("Date:");

        chDate.setDateFormatString("dd/MM/yyyy");

        jLabel4.setText("Encoder:");

        txtEncoder.setBackground(new java.awt.Color(204, 204, 204));
        txtEncoder.setEditable(false);
        txtEncoder.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel5.setText("Comment On Income:");

        txtComment.setColumns(20);
        txtComment.setLineWrap(true);
        jScrollPane1.setViewportView(txtComment);

        jLabel6.setText("Receipt Number:");

        jLabel7.setText("Record Id:");

        txtId.setBackground(new java.awt.Color(204, 204, 204));
        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbIncomeType, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chDate, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(txtReceiptNumber))))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38))
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIncomeAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtEncoder, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbIncomeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtReceiptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIncomeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEncoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(chDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Exit");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    clear();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    save();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton6ActionPerformed

private void txtIncomeAmountCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIncomeAmountCaretUpdate
    if (!txtIncomeAmount.getText().isEmpty()) {
        try {
            Integer.parseInt(txtIncomeAmount.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Enter Income Amount as a number please");
        }
    }
}//GEN-LAST:event_txtIncomeAmountCaretUpdate

private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtIdActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    search();
}//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser chDate;
    private javax.swing.JComboBox cmbIncomeType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtEncoder;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIncomeAmount;
    private javax.swing.JTextField txtReceiptNumber;
    // End of variables declaration//GEN-END:variables
}
