/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrayerRequestViewerGUI.java
 *
 * Created on May 9, 2012, 11:20:28 AM
 */
package orm.dao.Impl.GUI;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import orm.Christian;
import orm.DAOFactory;
import orm.PrayerRequest;

/**
 *
 * @author jean pierre
 */
public class PrayerRequestViewerGUI extends javax.swing.JInternalFrame {

    private DAOFactory daoFactory = DAOFactory.getInstance();

    /** Creates new form PrayerRequestViewerGUI */
    public PrayerRequestViewerGUI() {
        initComponents();
        setChristian();
        dateFrom.setEnabled(false);
        dateTo.setEnabled(false);
    }

    private void setChristian() {
        cmbChristian.removeAllItems();
        for (Christian c : daoFactory.getChristianDAO().findActive()) {
            cmbChristian.addItem(c.getChristianPin());
        }
    }

    private void clear() {
        clearTable();
    }

    private void clearTable() {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("First Name");
        tableHeaders.add("Last Name");
        tableHeaders.add("Prayer Intention");
        tableHeaders.add("Request Date");
        tableHeaders.add("Request Type");
        tableHeaders.add("Prefered Prayer Date");
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add("");
        oneRow.add("");
        oneRow.add("");
        oneRow.add("");
        oneRow.add("");
        oneRow.add("");
        tableData.add(oneRow);
        table.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCriteria = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbChristian = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dateTo = new com.toedter.calendar.JDateChooser();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Prayer Request Viewer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Criteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 153, 0)));

        jLabel1.setText("Criteria:");

        cmbCriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Christian", "Dates", "Christian and Dates" }));
        cmbCriteria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCriteriaItemStateChanged(evt);
            }
        });
        cmbCriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbCriteriaKeyPressed(evt);
            }
        });

        jLabel2.setText("Christian:");

        cmbChristian.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbChristian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbChristianItemStateChanged(evt);
            }
        });

        jLabel3.setText("Date From:");

        dateFrom.setDateFormatString("dd/MM/yyyy");

        jLabel4.setText("Date To:");

        dateTo.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbChristian, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(dateTo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(cmbCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cmbChristian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, -1, -1));

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 153, 0)));
        panel.setAutoscrolls(true);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Prayer Intention", "Request Date", "Request Type", "Prefered Prayer Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, -1, -1));

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setRollover(true);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Display Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Exit");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 708, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbCriteriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCriteriaItemStateChanged
    if (cmbCriteria.getSelectedIndex() == 0) {
        cmbChristian.enable();
        dateFrom.setEnabled(false);
        dateTo.setEnabled(false);
        setChristian();
    }
    if (cmbCriteria.getSelectedIndex() == 1) {
        dateFrom.setEnabled(true);
        dateTo.setEnabled(true);
        cmbChristian.removeAllItems();
        cmbChristian.enable(false);
    }
    if (cmbCriteria.getSelectedIndex() == 2) {
        cmbChristian.enable();
        dateFrom.setEnabled(true);
        dateTo.setEnabled(true);
        setChristian();
    }
}//GEN-LAST:event_cmbCriteriaItemStateChanged

private void cmbChristianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbChristianItemStateChanged
    try {
        Christian c = daoFactory.getChristianDAO().findByChristianPin((String) cmbChristian.getSelectedItem());
        cmbChristian.setToolTipText(c.getFullName());
    } catch (Exception ex) {
    }
}//GEN-LAST:event_cmbChristianItemStateChanged

private void cmbCriteriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCriteriaKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_cmbCriteriaKeyPressed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    List<PrayerRequest> result = new ArrayList<PrayerRequest>();
    if (cmbCriteria.getSelectedIndex() == 0) {
        result = daoFactory.getPrayerRequestDAO().findByRequestor((String) cmbChristian.getSelectedItem());
    }
    if (cmbCriteria.getSelectedIndex() == 1) {
        if (dateFrom.getDate().compareTo(dateTo.getDate()) <= 0) {
            result = daoFactory.getPrayerRequestDAO().findByDates(dateFrom.getDate(), dateTo.getDate());
        } else {
            JOptionPane.showMessageDialog(null, "Date From must be greater or equal to Date To");
        }
    }
    if (cmbCriteria.getSelectedIndex() == 2) {
        if (dateFrom.getDate().compareTo(dateTo.getDate()) <= 0) {
            result = daoFactory.getPrayerRequestDAO().findByPreferedDatesAndRequest(dateFrom.getDate(), dateTo.getDate(), (String) cmbChristian.getSelectedItem());
        } else {
            JOptionPane.showMessageDialog(null, "Date From must be greater or equal to Date To");
        }
    }
    if (!result.isEmpty()) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("First Name");
        tableHeaders.add("Last Name");
        tableHeaders.add("Prayer Intention");
        tableHeaders.add("Request Date");
        tableHeaders.add("Request Type");
        tableHeaders.add("Prefered Prayer Date");
        for (PrayerRequest request : result) {
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(request.getChristian().getFirstName());
            oneRow.add(request.getChristian().getLastName());
            oneRow.add(request.getPrayerIntention());
            oneRow.add(request.getRequestDate().toString());
            oneRow.add(request.getRequestType());
            oneRow.add(request.getPreferedPrayerDate().toString());
            tableData.add(oneRow);
        }
        table.setModel(new DefaultTableModel(tableData, tableHeaders));
    } else {
        JOptionPane.showMessageDialog(null, "No Result Found");
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    clear();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton6ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbChristian;
    private javax.swing.JComboBox cmbCriteria;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
